### ISSUE TITLE
Is this ready now , what's the readme or wiki?

### ISSUE THREAD

**Issue by SeekPoint** [saist1993/tensor-related-activities#1]

**Comment by geraltofrivia** [comment]
Hey, I'm really sorry to say but this repo is very half baked at the moment. I'm working on it right now, in fact. Unfortunately, it'll be atleast a week before the repo is usable and thereafter, a comprehensive readme will follow.

Apologies,

**Comment by SeekPoint** [comment]
so expecting, great job! @geraltofrivia
